# App
spring.application.name=hotelia-backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/hotelia?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
app.jwt.secret=hoteliaSecretKey2024VeryLongSecretKeyForJWTSigning
app.jwt.expiration=86400000

# Server
server.port=8080